apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    openshift.io/description: "Storage for workbench" 
    openshift.io/display-name: workbench
  name: workbench-storage
  finalizers:
    - kuberntes.io/pvc-protection
  labels:
    opendatahub.io/dashboard: 'true'  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  storageClassName: gp3-csi
